// usage: node demo.js <base-url> <out-dir>  — the scripted demo, end to end
const { chromium } = require('playwright');
const [base, out] = process.argv.slice(2);
const sleep = ms => new Promise(r => setTimeout(r, ms));
const R = []; const check = (n, ok, x = '') => R.push(`${ok ? 'PASS' : 'FAIL'}  ${n}${x ? '  · ' + x : ''}`);
(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  const errs = []; page.on('pageerror', e => errs.push(e.message));
  const t0 = Date.now();
  await page.goto(base + 'demo?skipboot'); await sleep(1500);
  check('demo: no home screen over it', !(await page.$eval('#menu', e => e.classList.contains('show'))));
  check('demo: breadcrumb says Demo', /Demo/.test(await page.textContent('#crumbs')));
  await page.waitForSelector('#askbar.show', { timeout: 60000 });
  const askAt = (Date.now() - t0) / 1000;
  check('the question arrives in the bar above the console', true, `${askAt.toFixed(0)} s`);
  const steps = await page.$$eval('#steps .s', els => els.map(e => e.className.replace('s', '').trim() + ':' + e.textContent));
  check('the stepper moved past planning', steps.some(s => /now:Review|now:Build/.test(s)), steps.join(' '));
  await page.screenshot({ path: `${out}/demo-ask.png` });
  const opts = await page.$$eval('#askbar .opts button', els => els.map(e => e.textContent));
  check('the question asks you to write, no canned options', opts.length === 1 && opts[0] === 'Answer', opts.join(' | '));
  await page.click('#askbar .opts button >> nth=0'); await sleep(400);
  check('the answer box is a plain text box', (await page.textContent('#askLbl')).startsWith('Your answer') && !(await page.$$eval('#askOpts button', b => b.length)));
  await page.click('#askSend'); await sleep(200);
  check('an empty answer is refused with a hint', /Write an answer first/.test(await page.textContent('#askErr')));
  await page.fill('#askText', 'no matter where you go, everyone is connected <b>');
  await page.screenshot({ path: `${out}/demo-answer.png` });
  await page.click('#askSend'); await sleep(900);
  check('your line goes back to the council', /everyone is connected/.test(await page.textContent('#feed')));
  await page.waitForSelector('#consensus.show', { timeout: 70000 });
  check('the demo reaches consensus', true, `${((Date.now() - t0) / 1000).toFixed(0)} s`);
  const buttons = await page.$$eval('#consensus .next button', els => els.filter(e => e.offsetParent !== null).map(e => e.textContent));
  check('consensus offers Open the page', buttons.includes('Open the page'), buttons.join(' | '));
  const built = await page.$$eval('#built .brow', els => els.map(e => e.innerText.replace(/\s+/g, ' ')));
  check('CONSENSUS lists what was built, each with Open', built.length === 2 && built.every(r => /Open/.test(r)), built.join(' | '));
  await page.screenshot({ path: `${out}/demo-consensus.png` });
  await page.evaluate(() => hide('#consensus'));
  await page.click('#tabs button[data-tab="files"]'); await sleep(300);
  const files = await page.$$eval('#artlist .frow b', els => els.map(e => e.textContent));
  check('Files tab lists both deliverables', files.length === 2, files.join(' | '));
  await page.click('#artlist .frow >> nth=1'); await sleep(400);
  check('the ADR opens as a document and records your line', await page.$eval('#mdoc', e => e.classList.contains('show') && /hello, world/.test(e.textContent) && /everyone is connected/.test(e.textContent)));
  const hello = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  const herrs = []; hello.on('pageerror', e => herrs.push(e.message));
  const url = await page.evaluate(() => helloUrl());
  await hello.goto(base + url.slice(1)); await sleep(6500);
  check('the hello page renders', /hello, world/.test(await hello.textContent('h1')));
  const line = await hello.textContent('#line');
  check('the page types your line, as text (no HTML)', line === 'no matter where you go, everyone is connected <b>' && !(await hello.$('#line b')), line);
  check('PRESENT DAY / PRESENT TIME stays as the easter egg', /PRESENT DAY\s*\d{4}\.\d\d\.\d\d\s*PRESENT TIME\s*\d\d:\d\d:\d\d/.test(await hello.textContent('.clock')), await hello.textContent('.clock'));
  await hello.screenshot({ path: `${out}/demo-hello.png` });
  console.log(R.join('\n')); console.log('page errors:', errs.length || herrs.length ? [...errs, ...herrs] : 'none');
  await browser.close();
  process.exit(R.some(r => r.startsWith('FAIL')) || errs.length ? 1 : 0);
})().catch(e => { console.log(R.join('\n')); console.error('DEMO FAIL', e.message); process.exit(1); });
