"""docs/BENCHMARKS.md from bench/results.jsonl: the newest run of each task on each engine.
usage: python3 bench/report.py"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
ORDER = ["claude", "local", "codex", "local-codex", "gemini"]
NAMES = {"claude": "Claude", "local": "Local (Ollama)", "codex": "Codex", "local-codex": "Local via Codex", "gemini": "Gemini"}
TASKS = {"quick-hello": "A hello page", "quick-fix-test": "Fix a failing test", "standard-rate-limit": "A rate limiter, with tests",
         "thorough-sql-injection": "Fix an SQL injection, with a test"}


def kilo(n: int) -> str:
    return f"{n / 1e6:.1f}M" if n >= 1e6 else f"{round(n / 1e3)}k"


def took(s: int) -> str:
    return f"{s // 60} min {s % 60:02d} s" if s >= 60 else f"{s} s"


def cell(r: dict) -> str:
    if not r:
        return "not run"
    if not r["ended"]:
        return f"didn't finish in {took(r['secs'])}"
    mark = "pass" if r["check"] == "pass" else "**fail**"
    cost = "$0" if r["engine"].startswith("local") else f"${r['usd']:.2f}"
    return f"{mark} · {took(r['secs'])} · {kilo(r['tokens_in'] + r['tokens_out'])} tokens · {cost}"


def main():
    rows = [json.loads(x) for x in (HERE / "results.jsonl").read_text(encoding="utf-8").splitlines() if x.strip()]
    latest = {}
    for r in rows:
        latest[(r["engine"], r["task"])] = r
    engines = [e for e in ORDER if any(k[0] == e for k in latest)]
    tasks = [t for t in TASKS if any(k[1] == t for k in latest)]
    when = max((r["date"] for r in rows), default="")
    version = max((r["navi"] for r in rows), default="")
    out = [
        "# Benchmarks", "",
        "Real councils on real engines, on small tasks a script can check. Every number below is one run, so read them as",
        "a picture of how each engine behaves, not a ranking. Generated by `bench/report.py` from `bench/results.jsonl`.", "",
        f"*NAVI {version}, {when}. The Knights, Allow all, on an Apple M4 Pro (local models on the same machine).*", "",
        "| Task | Pace | " + " | ".join(NAMES[e] for e in engines) + " |",
        "|---|---|" + "---|" * len(engines),
    ]
    for t in tasks:
        pace = next(r["pace"] for k, r in latest.items() if k[1] == t)
        out.append(f"| {TASKS[t]} | {pace} | " + " | ".join(cell(latest.get((e, t), {})) for e in engines) + " |")
    missing = [NAMES[e] for e in ORDER if e not in engines]
    if missing:
        out += ["", f"*Not measured yet: {', '.join(missing)}.* Codex on OpenAI needs a ChatGPT or OpenAI account with quota",
                "left, Gemini a key or a login Google accepts, and the first Local-via-Codex runs were void (another run's",
                "member held the model the whole time; that bug is fixed)."]
    out += ["", "**Pass** means the task's check passed on what the council left behind: the check runs the code (with a fake",
            "clock, injection payloads, cases the council's own tests don't cover), not just the tests the council wrote.",
            "**Time** is from launch to the session's end. **Tokens** count everything the engine read and wrote, cached",
            "reads included; local models cost nothing.", "", "## What each run used", "",
            "| Engine | Task | Models | Restarts | Members run | Cards refused | Check |", "|---|---|---|---|---|---|---|"]
    for e in engines:
        for t in tasks:
            r = latest.get((e, t))
            if r:
                out.append(f"| {NAMES[e]} | {TASKS[t]} | {', '.join(r.get('models') or []) or '?'} | {r['restarts']} | "
                           f"{r['member_runs'] or '-'} | {r.get('cards') or '-'} | {r['why'] or r['check']} |")
    out += ["", "*Members run* counts members started with `navi run` (engines without registered members); on Claude Code",
            "members are registered subagents and don't show here. *Restarts* counts how often NAVI had to start the",
            "moderator again on the same conversation because it stopped before the session ended. *Cards refused*: permission",
            "cards the runner said no to (Allow all still asks before anything outside the project).", "",
            "## Run it yourself", "", "```bash",
            "python3 bench/run.py --engine local                  # every task on your local models (free)",
            "python3 bench/run.py --engine claude --tasks quick-hello",
            "python3 bench/report.py                              # rewrites this page", "```", "",
            "Each run gets a fresh git project and settings of its own (only your engine's model choices are copied), answers",
            "the council's questions the way a person would, and checks the result with the task's `check.py`. On paid",
            "engines it costs what the councils cost. The tasks are in [`bench/tasks`](../bench/tasks): a `task.json`, the",
            "`project/` it starts from, and the `check.py` that decides.", ""]
    (HERE.parent / "docs" / "BENCHMARKS.md").write_text("\n".join(out), encoding="utf-8")
    print(f"docs/BENCHMARKS.md: {len(latest)} runs, {len(engines)} engines")


if __name__ == "__main__":
    main()
